import { OptionType } from 'interfaces';

export const timeZones: OptionType[] = [
	{
		text: 'Select...',
		value: '',
		disabled: false,
		placeholder: true,
	},
	{ text: 'Africa/Ceuta', value: '+1', disabled: false, placeholder: false },
	{ text: 'Africa/Conakry', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Dakar', value: '0', disabled: false, placeholder: false },
	{
		text: 'Africa/Dar_es_Salaam',
		value: '+3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Africa/Djibouti', value: '+3', disabled: false, placeholder: false },
	{ text: 'Africa/Douala', value: '+1', disabled: false, placeholder: false },
	{ text: 'Africa/El_Aaiun', value: '+1', disabled: false, placeholder: false },
	{ text: 'Africa/Freetown', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Gaborone', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Harare', value: '+2', disabled: false, placeholder: false },
	{
		text: 'Africa/Johannesburg',
		value: '+2',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Africa/Juba', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Kampala', value: '+3', disabled: false, placeholder: false },
	{ text: 'Africa/Khartoum', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Kigali', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Kinshasa', value: '+1', disabled: false, placeholder: false },
	{ text: 'Africa/Lagos', value: '+1', disabled: false, placeholder: false },
	{
		text: 'Africa/Libreville',
		value: '+1',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Africa/Lome', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Luanda', value: '+1', disabled: false, placeholder: false },
	{
		text: 'Africa/Lubumbashi',
		value: '+2',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Africa/Lusaka', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Malabo', value: '+1', disabled: false, placeholder: false },
	{ text: 'Africa/Maputo', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Maseru', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Mbabane', value: '+2', disabled: false, placeholder: false },
	{
		text: 'Africa/Mogadishu',
		value: '+3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Africa/Monrovia', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Nairobi', value: '+3', disabled: false, placeholder: false },
	{ text: 'Africa/Ndjamena', value: '+1', disabled: false, placeholder: false },
	{ text: 'Africa/Niamey', value: '+1', disabled: false, placeholder: false },
	{
		text: 'Africa/Nouakchott',
		value: '0',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Africa/Ouagadougou',
		value: '0',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Africa/Porto-Novo',
		value: '+1',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Africa/Sao_Tome', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Timbuktu', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Tripoli', value: '+2', disabled: false, placeholder: false },
	{ text: 'Africa/Tunis', value: '0', disabled: false, placeholder: false },
	{ text: 'Africa/Windhoek', value: '+2', disabled: false, placeholder: false },
	{ text: 'America/Adak', value: '-10', disabled: false, placeholder: false },
	{
		text: 'America/Anchorage',
		value: '-9',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Anguilla',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Antigua', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Araguaina',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Buenos_Aires',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Catamarca',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/ComodRivadavia',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Cordoba',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Jujuy',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/La_Rioja',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Mendoza',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Rio_Gallegos',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Salta',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/San_Juan',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/San_Luis',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Tucuman',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Argentina/Ushuaia',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Aruba', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Asuncion',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Atikokan',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Atka', value: '-10', disabled: false, placeholder: false },
	{ text: 'America/Bahia', value: '-3', disabled: false, placeholder: false },
	{
		text: 'America/Bahia_Banderas',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Barbados',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Belem', value: '-3', disabled: false, placeholder: false },
	{ text: 'America/Belize', value: '-6', disabled: false, placeholder: false },
	{
		text: 'America/Blanc-Sablon',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Boa_Vista',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Bogota', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Boise', value: '-7', disabled: false, placeholder: false },
	{
		text: 'America/Buenos_Aires',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Cambridge_Bay',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Campo_Grande',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Cancun', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Caracas', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Catamarca',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Cayenne', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Cayman', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Chicago', value: '-6', disabled: false, placeholder: false },
	{
		text: 'America/Chihuahua',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Coral_Harbour',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Cordoba', value: '-3', disabled: false, placeholder: false },
	{
		text: 'America/Costa_Rica',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Creston', value: '-7', disabled: false, placeholder: false },
	{ text: 'America/Cuiaba', value: '-4', disabled: false, placeholder: false },
	{ text: 'America/Curacao', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Danmarkshavn',
		value: '0',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Dawson', value: '-7', disabled: false, placeholder: false },
	{
		text: 'America/Dawson_Creek',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Denver', value: '-7', disabled: false, placeholder: false },
	{ text: 'America/Detroit', value: '-5', disabled: false, placeholder: false },
	{
		text: 'America/Dominica',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Edmonton',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Eirunepe',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/El_Salvador',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Ensenada',
		value: '-8',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Fort_Nelson',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Fort_Wayne',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Fortaleza',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Glace_Bay',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Godthab', value: '-3', disabled: false, placeholder: false },
	{
		text: 'America/Goose_Bay',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Grand_Turk',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Grenada', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Guadeloupe',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Guatemala',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Guayaquil',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Guyana', value: '-4', disabled: false, placeholder: false },
	{ text: 'America/Halifax', value: '-4', disabled: false, placeholder: false },
	{ text: 'America/Havana', value: '-5', disabled: false, placeholder: false },
	{
		text: 'America/Hermosillo',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Indianapolis',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Knox',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Marengo',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Petersburg',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Tell_City',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Vevay',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Vincennes',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indiana/Winamac',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Indianapolis',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Inuvik', value: '-7', disabled: false, placeholder: false },
	{ text: 'America/Iqaluit', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Jamaica', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Jujuy', value: '-3', disabled: false, placeholder: false },
	{ text: 'America/Juneau', value: '-9', disabled: false, placeholder: false },
	{
		text: 'America/Kentucky/Louisville',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Kentucky/Monticello',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Knox_IN', value: '-6', disabled: false, placeholder: false },
	{
		text: 'America/Kralendijk',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/La_Paz', value: '-4', disabled: false, placeholder: false },
	{ text: 'America/Lima', value: '-5', disabled: false, placeholder: false },
	{
		text: 'America/Los_Angeles',
		value: '-8',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Louisville',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Lower_Princes',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Maceio', value: '-3', disabled: false, placeholder: false },
	{ text: 'America/Managua', value: '-6', disabled: false, placeholder: false },
	{ text: 'America/Manaus', value: '-4', disabled: false, placeholder: false },
	{ text: 'America/Marigot', value: '0', disabled: false, placeholder: false },
	{
		text: 'America/Martinique',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Matamoros',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Mazatlan',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Mendoza', value: '-3', disabled: false, placeholder: false },
	{
		text: 'America/Menominee',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Merida', value: '-6', disabled: false, placeholder: false },
	{
		text: 'America/Metlakatla',
		value: '-9',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Mexico_City',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Miquelon',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Moncton', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Monterrey',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Montevideo',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Montreal',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Montserrat',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Nassau', value: '-5', disabled: false, placeholder: false },
	{
		text: 'America/New_York',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Nipigon', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Nome', value: '-9', disabled: false, placeholder: false },
	{ text: 'America/Noronha', value: '-2', disabled: false, placeholder: false },
	{
		text: 'America/North_Dakota/Beulah',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/North_Dakota/Center',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/North_Dakota/New_Salem',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Nuuk', value: '-3', disabled: false, placeholder: false },
	{ text: 'America/Ojinaga', value: '-7', disabled: false, placeholder: false },
	{ text: 'America/Panama', value: '-5', disabled: false, placeholder: false },
	{
		text: 'America/Pangnirtung',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Paramaribo',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Phoenix', value: '-7', disabled: false, placeholder: false },
	{
		text: 'America/Port-au-Prince',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Port_of_Spain',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Porto_Acre',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Porto_Velho',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Puerto_Rico',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Punta_Arenas',
		value: '30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Rainy_River',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Rankin_Inlet',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Recife', value: '-3', disabled: false, placeholder: false },
	{ text: 'America/Regina', value: '-6', disabled: false, placeholder: false },
	{
		text: 'America/Resolute',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Rio_Branco',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Rosario', value: '-3', disabled: false, placeholder: false },
	{
		text: 'America/Santa_Isabel',
		value: '-8',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Santarem',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Santiago',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Santo_Domingo',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Sao_Paulo',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Scoresbysund',
		value: '-1',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Shiprock',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Sitka', value: '-9', disabled: false, placeholder: false },
	{
		text: 'America/St_Barthelemy',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/St_Johns',
		value: '-3:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/St_Kitts',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/St_Lucia',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/St_Thomas',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/St_Vincent',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Swift_Current',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Tegucigalpa',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Thule', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Thunder_Bay',
		value: '-5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Tijuana', value: '-8', disabled: false, placeholder: false },
	{ text: 'America/Toronto', value: '-5', disabled: false, placeholder: false },
	{ text: 'America/Tortola', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Vancouver',
		value: '-8',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Virgin', value: '-4', disabled: false, placeholder: false },
	{
		text: 'America/Whitehorse',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'America/Winnipeg',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'America/Yakutat', value: '-9', disabled: false, placeholder: false },
	{
		text: 'America/Yellowknife',
		value: '-7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Casey',
		value: '+11',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Davis',
		value: '+7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/DumontDUrville',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Macquarie',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Mawson',
		value: '+5',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/McMurdo',
		value: '+12',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Palmer',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Rothera',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/South_Pole',
		value: '+12',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Antarctica/Syowa',
		value: '+3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Antarctica/Troll', value: '0', disabled: false, placeholder: false },
	{
		text: 'Antarctica/Vostok',
		value: '+6',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Arctic/Longyearbyen',
		value: '+1',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Aden', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Almaty', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Amman', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Anadyr', value: '+12', disabled: false, placeholder: false },
	{ text: 'Asia/Aqtau', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Aqtobe', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Ashgabat', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Ashkhabad', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Atyrau', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Baghdad', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Bahrain', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Baku', value: '+4', disabled: false, placeholder: false },
	{ text: 'Asia/Bangkok', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Barnaul', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Beirut', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Bishkek', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Brunei', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Calcutta', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Chita', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Choibalsan', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Chongqing', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Chungking', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Colombo', value: '+5:30', disabled: false, placeholder: false },
	{ text: 'Asia/Dacca', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Damascus', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Dhaka', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Dili', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Dubai', value: '+4', disabled: false, placeholder: false },
	{ text: 'Asia/Dushanbe', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Famagusta', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Gaza', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Harbin', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Hebron', value: '+2', disabled: false, placeholder: false },
	{
		text: 'Asia/Ho_Chi_Minh',
		value: '+7',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Hong_Kong', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Hovd', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Irkutsk', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Istanbul', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Jakarta', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Jayapura', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Jerusalem', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Kabul', value: '+4:30', disabled: false, placeholder: false },
	{ text: 'Asia/Kamchatka', value: '+12', disabled: false, placeholder: false },
	{ text: 'Asia/Karachi', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Kashgar', value: '+6', disabled: false, placeholder: false },
	{
		text: 'Asia/Kathmandu',
		value: '+5:45',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Asia/Katmandu',
		value: '+5:45',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Khandyga', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Kolkata', value: '5:30', disabled: false, placeholder: false },
	{
		text: 'Asia/Krasnoyarsk',
		value: '+7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Asia/Kuala_Lumpur',
		value: '+8',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Kuching', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Kuwait', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Macao', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Macau', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Magadan', value: '+11', disabled: false, placeholder: false },
	{ text: 'Asia/Makassar', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Manila', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Muscat', value: '+4', disabled: false, placeholder: false },
	{ text: 'Asia/Nicosia', value: '+2', disabled: false, placeholder: false },
	{
		text: 'Asia/Novokuznetsk',
		value: '+7',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Asia/Novosibirsk',
		value: '+7',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Omsk', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Oral', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Phnom_Penh', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Pontianak', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Pyongyang', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Qatar', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Qostanay', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Qyzylorda', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Rangoon', value: '+6:30', disabled: false, placeholder: false },
	{ text: 'Asia/Riyadh', value: '+3', disabled: false, placeholder: false },
	{ text: 'Asia/Saigon', value: '+7', disabled: false, placeholder: false },
	{ text: 'Asia/Sakhalin', value: '+11', disabled: false, placeholder: false },
	{ text: 'Asia/Samarkand', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Seoul', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Shanghai', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Singapore', value: '+8', disabled: false, placeholder: false },
	{
		text: 'Asia/Srednekolymsk',
		value: '+11',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Taipei', value: '8', disabled: false, placeholder: false },
	{ text: 'Asia/Tashkent', value: '+5', disabled: false, placeholder: false },
	{ text: 'Asia/Tbilisi', value: '+4', disabled: false, placeholder: false },
	{ text: 'Asia/Tehran', value: '+3:30', disabled: false, placeholder: false },
	{ text: 'Asia/Tel_Aviv', value: '+2', disabled: false, placeholder: false },
	{ text: 'Asia/Thimbu', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Thimphu', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Tokyo', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Tomsk', value: '+7', disabled: false, placeholder: false },
	{
		text: 'Asia/Ujung_Pandang',
		value: '+8',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Asia/Ulaanbaatar',
		value: '+8',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Ulan_Bator', value: '+8', disabled: false, placeholder: false },
	{ text: 'Asia/Urumqi', value: '+6', disabled: false, placeholder: false },
	{ text: 'Asia/Ust-Nera', value: '+10', disabled: false, placeholder: false },
	{ text: 'Asia/Vientiane', value: '+7', disabled: false, placeholder: false },
	{
		text: 'Asia/Vladivostok',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Yakutsk', value: '+9', disabled: false, placeholder: false },
	{ text: 'Asia/Yangon', value: '+6:30', disabled: false, placeholder: false },
	{
		text: 'Asia/Yekaterinburg',
		value: '+5',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Asia/Yerevan', value: '+4', disabled: false, placeholder: false },
	{ text: 'Atlantic/Azores', value: '-1', disabled: false, placeholder: false },
	{
		text: 'Atlantic/Bermuda',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Atlantic/Canary', value: '0', disabled: false, placeholder: false },
	{
		text: 'Atlantic/Cape_Verde',
		value: '-1',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Atlantic/Faeroe', value: '0', disabled: false, placeholder: false },
	{ text: 'Atlantic/Faroe', value: '0', disabled: false, placeholder: false },
	{
		text: 'Atlantic/Jan_Mayen',
		value: '1',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Atlantic/Madeira', value: '0', disabled: false, placeholder: false },
	{
		text: 'Atlantic/Reykjavik',
		value: '0',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Atlantic/South_Georgia',
		value: '-2',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Atlantic/St_Helena',
		value: '0',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Atlantic/Stanley',
		value: '-3',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Australia/ACT', value: '+10', disabled: false, placeholder: false },
	{
		text: 'Australia/Adelaide',
		value: '+9:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Brisbane',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Broken_Hill',
		value: '+9:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Canberra',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Currie',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Darwin',
		value: '+9:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Eucla',
		value: '+8:45',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Hobart',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/LHI',
		value: '+10:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Lindeman',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Lord_Howe',
		value: '+10:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Melbourne',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/North',
		value: '+9:30',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Australia/NSW', value: '+10', disabled: false, placeholder: false },
	{ text: 'Australia/Perth', value: '+8', disabled: false, placeholder: false },
	{
		text: 'Australia/Queensland',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/South',
		value: '+9:30',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Sydney',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Tasmania',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Australia/Victoria',
		value: '+10',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Australia/West', value: '+8', disabled: false, placeholder: false },
	{
		text: 'Australia/Yancowinna',
		value: '+9:30',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Brazil/Acre', value: '-5', disabled: false, placeholder: false },
	{
		text: 'Brazil/DeNoronha',
		value: '-2',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Brazil/East', value: '-3', disabled: false, placeholder: false },
	{ text: 'Brazil/West', value: '-4', disabled: false, placeholder: false },
	{ text: 'Canada/Atlantic', value: '-4', disabled: false, placeholder: false },
	{ text: 'Canada/Central', value: '-6', disabled: false, placeholder: false },
	{ text: 'Canada/Eastern', value: '-5', disabled: false, placeholder: false },
	{ text: 'Canada/Mountain', value: '-7', disabled: false, placeholder: false },
	{
		text: 'Canada/Newfoundland',
		value: '-3:30',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Canada/Pacific', value: '-8', disabled: false, placeholder: false },
	{
		text: 'Canada/Saskatchewan',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Canada/Yukon', value: '-7', disabled: false, placeholder: false },
	{ text: 'CET', value: '+1', disabled: false, placeholder: false },
	{
		text: 'Chile/Continental',
		value: '-4',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Chile/EasterIsland',
		value: '-6',
		disabled: false,
		placeholder: false,
	},
];
